### ISSUE TITLE
add script with leukdata processing in inst/extdata

### ISSUE THREAD

**Issue by rmflight** [LucyMcGowan/sgpvalue#2]
Would be really nice to see *how* you processed the Golub data.

It doesn't change your results, but right now someone else is not going to get the same `leukdata` as you are without this script or Rmd.

**Comment by LucyMcGowan** [comment]
I totally agree — I recently also received an email request for this — in a 😞 for reproducible research, this was cleaned before I joined so I don’t have that script, but it’s on our radar & I am working to track it down.

**Comment by rmflight** [comment]
Yikes! I hope you find it. I know I followed some stuff from the Bioconductor tutorial on it, and the max value they recommended was 16000, which on log10 scale would be 4.2, but the max I see in `leukdata` is 3.8, so very odd.

And I know we are dealing w/ roughly the same set of genes, as `Golub_Merge` from `golubEsets` :package: has 7129 genes, vs the 7128 in `leukdata`.

**Comment by LucyMcGowan** [comment]
The script has been located! Please find it [here](https://github.com/LucyMcGowan/sgpvalue/blob/master/figures/GolubLeukemiaGeneData.R).  Essentially it was normalized based on the methods described in Efron's _Large Scale Inference_ (2010), section 6.1, page 91.
